name: production

on:
  push:
    branches:
      - production

jobs:
  staging:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: add file
        run: |
          echo production > public/date.txt
          echo `date` >> public/date.txt

      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add public
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" -a | exit 0
      - name: push
        run: git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" --follow-tags -f | exit 0
