name: staging

on:
  push:
    branches:
      - staging

jobs:
  staging:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          cp src/index.html public/index.html
          sed -i 's/{stage}/staging/g' public/index.html
          sed -i "s/{date}/`date`/g" public/index.html

      - name: checkout branch for publish
        run: git checkout -b staging-public

      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add public
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" -a | exit 0
      - name: push
        run: git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" --follow-tags -f | exit 0
